### ISSUE TITLE
no-labels has invalid config

### ISSUE THREAD

**Issue by alexweber** [feross/eslint-config-standard#25] opened 2016-02-11 14:03 UTC
Getting the following error:

`Error: standard:
	Configuration for rule "no-labels" is invalid:
	Value "2,[object Object]" has more items than allowed.`

Using the following versions:
- "eslint": "^2.0.0-rc.1",
- "eslint-config-standard": "^5.1.0",
- "eslint-plugin-promise": "^1.0.8",
- "eslint-plugin-standard": "^1.3.2",

**Comment by feross** [comment] 2016-02-12 06:21
Duplicate of https://github.com/feross/eslint-config-standard/issues/23

`eslint-config-standard` v5.0.0 is designed for use with `eslint` v2.0.0, which is due to be released soon.

Try updating eslint: `npm install eslint@2.0.0-rc.0`.

The release candidate (RC) version of eslint v2.0.0 is quite stable and already ready for use, IMO. But if you're conservative, I'd wait until the stable v2.0.0 release before upgrading to `eslint-config-standard` v5.0.0.

**Closed by feross** 2016-02-12 06:21 UTC
